export const produtos = [
  { nome: "Arroz", preco: 5.49 },
  { nome: "Feijão", preco: 6.29 },
  { nome: "Macarrão", preco: 3.79 },
  { nome: "Leite", preco: 4.99 },
  { nome: "Café", preco: 9.90 },
  { nome: "Açúcar", preco: 3.25 },
  { nome: "Farinha de trigo", preco: 4.50 },
  { nome: "Óleo de soja", preco: 6.10 },
  { nome: "Sabão em pó", preco: 8.45 },
  { nome: "Detergente", preco: 2.35 },
  { nome: "Shampoo", preco: 11.20 },
  { nome: "Condicionador", preco: 12.00 },
  { nome: "Papel higiênico (4 rolos)", preco: 6.75 },
  { nome: "Creme dental", preco: 3.89 },
  { nome: "Escova de dentes", preco: 4.59 },
  { nome: "Sabonete", preco: 2.15 },
  { nome: "Desodorante", preco: 9.49 },
  { nome: "Margarina", preco: 5.29 },
  { nome: "Queijo", preco: 19.90 },
  { nome: "Presunto", preco: 14.75 },
  { nome: "Pão de forma", preco: 7.80 },
  { nome: "Manteiga", preco: 8.90 },
  { nome: "Iogurte", preco: 3.45 },
  { nome: "Refrigerante 2L", preco: 7.50 },
  { nome: "Água mineral 1,5L", preco: 2.70 },
  { nome: "Suco de caixinha", preco: 4.90 },
  { nome: "Bolacha recheada", preco: 2.99 },
  { nome: "Achocolatado em pó", preco: 6.20 },
  { nome: "Molho de tomate", preco: 2.49 },
  { nome: "Milho verde (lata)", preco: 3.10 }
]
 